version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: spotify_party_django
    ports:
      - '8000:8000'
    volumes:
      - ./backend/db.sqlite3:/usr/src/app/db.sqlite3
    depends_on:
      - sqlite3

  frontend:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    container_name: spotify_party_react
    ports:
      - '3000:80'
    depends_on:
      - backend

  sqlite3:
    container_name: spotify_party_sqlite3
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - '9000:9000' 
    volumes:
      - ./backend/db.sqlite3:/root/db/db.sqlite3
    restart: unless-stopped

volumes:
  spotify_party_db_data:
